{-# OPTIONS --sized-types #-}

module Everything where
import Data.Pred
import Data.Relation
import Data.Environment
import Data.Var.Varlike
import Data.Var
import Stdlib
import Motivation.Problem.Naive
import Motivation.Problem.WithLibrary
import Motivation.POPLMark2.Sums
import Motivation.POPLMark2.GodelT
import Motivation.POPLMark2.STLC
import Generic.Fusion.Utils
import Generic.Fusion.Elaboration.LetBinder
import Generic.Fusion.Syntactic
import Generic.Fusion.Specialised.Propositional
import Generic.Fusion.Specialised.Replication
import Generic.Semantics
import Generic.Simulation.Syntactic
import Generic.Fundamental
import Generic.Context
import Generic.Relator
import Generic.Semantics.NbyE
import Generic.Semantics.TypeChecking
import Generic.Semantics.Elaboration.State
import Generic.Semantics.Elaboration.Typed
import Generic.Semantics.Elaboration.LetCounter
import Generic.Semantics.Elaboration.LetBinders
import Generic.Semantics.Elaboration.LetBinder
import Generic.Semantics.Unit
import Generic.Semantics.Syntactic
import Generic.Semantics.Contract
import Generic.Semantics.Printing
import Generic.Identity
import Generic.Examples.NbyE
import Generic.Examples.Colist
import Generic.Examples.SystemF
import Generic.Examples.Printing
import Generic.Examples.HuttonsRazor
import Generic.Fusion
import Generic.Syntax
import Generic.Equality
import Generic.Bisimilar
import Generic.Closure
import Generic.Focus
import Generic.Simulation
import Generic.Cofinite
import Generic.Scopecheck
import Generic.Syntax.PHOAS
import Generic.Syntax.STLC+State
import Generic.Syntax.Bidirectional
import Generic.Syntax.UTLC
import Generic.Syntax.LetCounter
import Generic.Syntax.STLC+Product
import Generic.Syntax.LetBinders
import Generic.Syntax.STLC
import Generic.Syntax.LetBinder
import Generic
import TableOfContent
import StateOfTheArt.ACMM
import StateOfTheArt.CDMM
